export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const ADD_PROFILE_POST = 'ADD_PROFILE_POST'
export const DELETE_PROFILE_POST = 'DELETE_PROFILE_POST'
export const UPDATE_PROFILE_POST = 'UPDATE_PROFILE_POST'

export const ADD_COLLECTION = 'ADD_COLLECTION'
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'

export const ADD_PROFILE_COLLECTION = 'ADD_PROFILE_COLLECTION'
export const UPDATE_PROFILE_COLLECTION = 'UPDATE_PROFILE_COLLECTION'
export const DELETE_PROFILE_COLLECTION = 'DELETE_PROFILE_COLLECTION'

export const ADD_COLLECTION_POST = 'ADD_COLLECTION_POST'

export const ADD_USER = 'ADD_USER'
export const LOG_IN_USER = 'LOG_IN_USER'
