export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'

export const ADD_COLLECTION = 'ADD_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'

export const ADD_COLLECTION_POST = 'ADD_COLLECTION_POST'
